apiVersion: v1
kind: Service
metadata:
  name: media-extractor
  namespace: sieve
  labels:
    app: media-extractor
spec:
  type: ClusterIP
  selector:
    app: media-extractor
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
