apiVersion: v1
kind: Service
metadata:
  name: text-extractor
  namespace: sieve
  labels:
    app: text-extractor
spec:
  type: ClusterIP
  selector:
    app: text-extractor
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: metrics
